In [20]:
import streamlit as st
import pandas as pd
import urllib
import json
from src.project1.helpers import *

In [21]:
station_url = 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status.json'
latlon_url = 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information'

In [22]:
df1 = query_station_status(station_url)

2025-03-04 03:20:34.025 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-03-04 03:20:34.027 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-04 03:20:34.746
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run e:\GI-AIWMD\Quarter 3\Sir Zia Project\Final_Streamlit_projects_By Sir Zia\Project1\.venv\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-03-04 03:20:34.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-04 03:20:34.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-04 03:20:35.282 Thread 'Thread-9': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-04 03:20:35.299 Thread 'Thread-9': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-04 03:20:37.957 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-04 03:20:37.957 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [23]:
df2 = get_station_latlon(latlon_url)

In [24]:
join_latlon(df1,df2)

,station_id,num_bikes_available,num_bikes_available_types,num_bikes_disabled,num_docks_available,num_docks_disabled,last_reported,is_charging_station,status,is_installed,is_renting,is_returning,traffic,mechanical,ebike,lat,lon
0,7000,4,"{'mechanical': 4, 'ebike': 0}",0,42,1,2025-03-03 22:17:59,False,IN_SERVICE,1,1,1,None,4,0,43.639832,-79.395954
1,7001,4,"{'mechanical': 4, 'ebike': 0}",0,19,0,2025-03-03 22:19:43,True,IN_SERVICE,1,1,1,None,4,0,43.664964,-79.383550
2,7002,1,"{'mechanical': 1, 'ebike': 0}",2,13,1,2025-03-03 22:18:04,False,IN_SERVICE,1,1,1,None,1,0,43.667131,-79.399555
3,7003,0,"{'mechanical': 0, 'ebike': 0}",0,14,1,2025-03-03 22:19:36,False,IN_SERVICE,1,1,1,None,0,0,43.667018,-79.402796
4,7005,15,"{'mechanical': 15, 'ebike': 0}",0,7,0,2025-03-03 22:19:09,False,IN_SERVICE,1,1,1,None,15,0,43.648001,-79.383177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,8016,7,"{'mechanical': 7, 'ebike': 0}",2,14,0,2025-03-03 22:19:51,False,IN_SERVICE,1,1,1,None,7,0,43.642499,-79.372858
863,8017,3,"{'mechanical': 3, 'ebike': 0}",0,12,0,2025-03-03 22:19:13,False,IN_SERVICE,1,1,1,None,3,0,43.725345,-79.297687
864,8018,3,"{'mechanical': 3, 'ebike': 0}",1,11,0,2025-03-03 22:19:56,False,IN_SERVICE,1,1,1,None,3,0,43.658977,-79.347153
865,8019,0,"{'mechanical': 0, 'ebike': 0}",0,15,0,2025-03-03 22:20:00,False,IN_SERVICE,1,1,1,None,0,0,43.680567,-79.390830
866,8020,8,"{'mechanical': 8, 'ebike': 0}",0,0,1,2025-03-03 22:20:21,False,IN_SERVICE,1,1,1,None,8,0,43.646568,-79.407687